name: Set variables
description: Set some useful variables
inputs:
  release_production_tag:
    description: Release-production latest tag
    default: release-production-eu
    required: true
outputs:
  prodVersion:
    description: Current production version
    value: ${{ steps.version.outputs.prodVersion }}
  masterVersion:
    description: Master version. must be higher than current prod
    value: ${{ steps.version.outputs.masterVersion }}
  hotfixVersion:
    description: Hotfix version for current prod version
    value: ${{ steps.version.outputs.hotfixVersion }}
runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      name: Set version
      id: version
      with:
        script: |
          const releaseProductionTagName = '${{ inputs.release_production_tag }}'
          const owner = context.repo.owner
          const repo = context.repo.repo
          const allTags = await github.rest.repos.listTags({ owner, repo });
          const branches = await github.rest.repos.listBranches({ owner, repo, per_page: 100, direction: 'asc', sort: 'updated' })
          const getVersionArr = (str) => {
            try{
              const versionStr = str.match(/(\d{1,3}.\d{1,3}.\d{1,3})/)[0]
              return versionStr.split('.')
            } catch {
              console.log('String does not contain version:',str)
              return false
            }
          }
          const sortVersions = (a,b) => (getVersionArr(b.name).join('') - getVersionArr(a.name).join(''))

          const getLatestDeployedReleaseTag = (arr,sha,name) => {
            const onlyTagsWithVersions = arr.filter(t => {
              console.log('t',t)
              console.log('getVersionArr(t.name)',getVersionArr(t.name))
              console.log('t.commit.sha == sha',t.commit.sha == sha)
              console.log('t.name != name',t.name != name)
              getVersionArr(t.name) && (t.commit.sha == sha) && (t.name != name)
            })
            console.log('onlyTagsWithVersions',onlyTagsWithVersions)
            return onlyTagsWithVersions.sort(sortVersions)[0]
          }

          const highestVersionReleaseBranch = branches.data.filter(br => br.name.includes('release-') && getVersionArr(br.name) ).sort(sortVersions)[0]

          console.log('highestVersionReleaseBranch:',highestVersionReleaseBranch.name)
          const [m1,m2,m3] = getVersionArr(highestVersionReleaseBranch.name)
          const masterVersion = [m1,+m2 + 1, 0].join('.')
          console.log('masterVersion',masterVersion)

          console.log('allTags',allTags)
          const releaseProductionTag = allTags.data.find(t => t.name == releaseProductionTagName)
          console.log('releaseProductionTag',releaseProductionTag)
          console.log('1')
          const latestDeployedReleaseTag = getLatestDeployedReleaseTag(allTags.data,releaseProductionTag.commit.sha,releaseProductionTag.name)
          console.log('2')
          console.log('latestDeployedReleaseTag:',latestDeployedReleaseTag.name)
          console.log('3')
          const [a,b,c] = getVersionArr(latestDeployedReleaseTag.name)
          const prodVersion = [a,b,c].join('.')
          const hotfixVersion = [a,b,+c + 1].join('.')

          console.log('prodVersion',prodVersion)
          console.log('hotfixVersion',hotfixVersion)
          console.log(`::set-output name=prodVersion::${prodVersion}`)
          console.log(`::set-output name=masterVersion::${masterVersion}`)
          console.log(`::set-output name=hotfixVersion::${hotfixVersion}`)
