name: Set variables
description: Set some useful variables
inputs:
  release_production_tag:
    description: Release-production latest tag
    default: release-production-eu
    required: true
outputs:
  prodVersion:
    description: Current production version
    value: ${{ steps.version.outputs.prodVersion }}
  masterVersion:
    description: Master version. must be higher than current prod
    value: ${{ steps.version.outputs.masterVersion }}
  hotfixVersion:
    description: Hotfix version for current prod version
    value: ${{ steps.version.outputs.hotfixVersion }}
runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      name: Set version
      id: version
      with:
        script: |
          const prodTagName = '${{ inputs.release_production_tag }}'
          const owner = context.repo.owner
          const repo = context.repo.repo
          const tags = await github.rest.repos.listTags({ owner, repo });
          const branches = await github.rest.repos.listBranches({ owner, repo })
          console.log('branches',branches.data)
          const getVersionArr = (str) => (str.match(/(\d{1,3}.\d{1,3}.\d{1,3})/)['0.0.0.0'])[0].split('.')

          const lastReleaseBranch = branches.data.sort((a,b) => getVersionArr(b.name).join('') - getVersionArr(a.name).join('') )[0]
          console.log('lastReleaseBranch',lastReleaseBranch)
          const [x,y,z] = getVersionArr(lastReleaseBranch.name)
          const masterVersion = [z,+y + 1, 0].join('.')
          console.log('masterVersion',masterVersion)

          prodTag = tags.data.find(t => t.name == prodTagName)
          releaseTag = tags.data.find(t => (t.commit.sha == prodTag.commit.sha) && (t.name != prodTag.name) )
          console.log('releaseTag',releaseTag)
          const [a,b,c] = getVersionArr(releaseTag.name)
          const hotfixVersion = [a,b,+c + 1].join('.')
          console.log('prodVersion',prodVersion)
          console.log('hotfixVersion',hotfixVersion)
          console.log(`::set-output name=prodVersion::${prodVersion}`)
          console.log(`::set-output name=masterVersion::${masterVersion}`)
          console.log(`::set-output name=hotfixVersion::${hotfixVersion}`)
